# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJA91ziXG9056e-OAyOAAAeVN81-fWWp
"""

#

"""#Problem statement :
Vino Veritas has observed significant variation in the quality ratings of its red wine products despite maintaining consistent fermentation processes. This inconsistency affects customer satisfaction, brand reputation, and product standardization.

The company needs to identify which chemical and physical properties of the wine most strongly influence quality and how these factors contribute to rating fluctuations. By analyzing the available dataset of wine attributes (such as acidity levels, sugar content, chlorides, alcohol, and other variables), the goal is to uncover key drivers of quality and provide data-driven recommendations to improve consistency and overall wine quality.

# Task
Analyze a wine quality dataset to identify key chemical and physical properties that influence wine quality, and provide data-driven recommendations to improve consistency and overall wine quality.

## Present Problem Statement

### Subtask:
Start the project by presenting the problem statement as a clear heading, as requested by Vino Veritas.

```markdown
# Problem Statement: Analyzing Wine Quality for Vino Veritas

This project aims to analyze a wine quality dataset to identify key chemical and physical properties that influence wine quality. The goal is to provide data-driven recommendations to Vino Veritas to improve the consistency and overall quality of their wines.
```

# Problem Statement: Analyzing Wine Quality for Vino Veritas

This project aims to analyze a wine quality dataset to identify key chemical and physical properties that influence wine quality. The goal is to provide data-driven recommendations to Vino Veritas to improve the consistency and overall quality of their wines.

## Load and Initial Data Inspection

### Subtask:
Load the wine quality dataset into a pandas DataFrame. Perform initial data inspections using functions like `df.head()`, `df.info()`, and `df.describe()` to understand the data structure, types, and basic statistics. Explain the purpose of each command.

**Reasoning**:
First, I'll import the pandas library to work with DataFrames. Then, I'll load the specified CSV file into a DataFrame, and display the first few rows to get an initial look at the data.
"""

import pandas as pd

df = pd.read_csv('/content/sample_data/winequality-red_par.csv')

print("First 5 rows of the DataFrame:")
display(df.head())

print("\nConcise summary of the DataFrame (data types, non-null values, memory usage):")
df.info()

print("\nDescriptive statistics of the DataFrame:")
display(df.describe())

print(df.count())



"""# Task
## Exploratory Data Analysis (EDA)

### Subtask:
Conduct a thorough EDA to visualize and understand the relationships within the dataset. This includes generating histograms with Kernel Density Estimation (KDE) plots for all chemical and physical properties, analyzing the distribution of the 'quality' rating, and computing and visualizing a correlation matrix as a heatmap to identify initial relationships between features and the 'quality' target.

## Exploratory Data Analysis (EDA)

### Subtask:
Conduct a thorough EDA to visualize and understand the relationships within the dataset. This includes generating histograms with Kernel Density Estimation (KDE) plots for all chemical and physical properties, analyzing the distribution of the 'quality' rating, and computing and visualizing a correlation matrix as a heatmap to identify initial relationships between features and the 'quality' target.

**Reasoning**:
I need to import the `matplotlib.pyplot` and `seaborn` libraries to perform the requested visualizations for EDA.
"""

import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries matplotlib.pyplot and seaborn imported successfully.")

"""**Reasoning**:
The next step is to generate histograms with Kernel Density Estimation (KDE) plots for all chemical and physical properties (excluding 'quality'), visualize the distribution of the 'quality' rating separately, and then compute and visualize a correlation matrix as a heatmap. This addresses all remaining parts of the EDA subtask.


"""

columns_to_plot = df.drop(columns=['quality']).columns
num_cols = len(columns_to_plot)
n_cols = 3  # Number of columns for the subplot grid
n_rows = (num_cols + n_cols - 1) // n_cols  # Calculate number of rows needed

plt.figure(figsize=(n_cols * 5, n_rows * 4))
plt.suptitle('Distribution of Chemical and Physical Properties', fontsize=16, y=1.02)

for i, column in enumerate(columns_to_plot):
    plt.subplot(n_rows, n_cols, i + 1)
    sns.histplot(df[column], kde=True)
    plt.title(f'Distribution of {column}')
    plt.xlabel(column)
    plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

# Distribution of 'quality' rating
plt.figure(figsize=(7, 5))
sns.histplot(df['quality'], kde=True, bins=range(min(df['quality']), max(df['quality']) + 2), discrete=True)
plt.title('Distribution of Wine Quality Rating')
plt.xlabel('Quality Rating')
plt.ylabel('Frequency')
plt.xticks(range(min(df['quality']), max(df['quality']) + 1))
plt.tight_layout()
plt.show()

# Correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Wine Properties')
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x=df['quality'])
plt.title("Wine Quality Count")
plt.xlabel("Quality")
plt.ylabel("Number of Wines")
plt.show()

"""## Data Preprocessing

### Subtask:
Prepare the data for machine learning by checking for and handling any missing values, and scaling numerical features using StandardScaler to normalize their range.

**Reasoning**:
The first step in data preprocessing is to check for any missing values in the DataFrame. I will use the `.isnull().sum()` method to identify columns with missing values and their respective counts. This is crucial for deciding on an appropriate handling strategy.
"""

print("Missing values in each column:")
print(df.isnull().sum())

"""**Reasoning**:
Since there are no missing values, the next step is to scale the numerical features. I will import `StandardScaler` from `sklearn.preprocessing`, identify the numerical columns (all except 'quality'), apply `StandardScaler` to these columns, and then display the head and descriptive statistics of the modified DataFrame to confirm the scaling.


"""

from sklearn.preprocessing import StandardScaler

# Identify numerical features to scale (all columns except 'quality')
numerical_features = df.drop(columns=['quality']).columns

# Instantiate StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the numerical features
df[numerical_features] = scaler.fit_transform(df[numerical_features])

print("DataFrame after scaling numerical features:")
display(df.head())

print("\nDescriptive statistics after scaling:")
display(df.describe())

"""## Model Selection and Training

### Subtask:
Select and train a suitable machine learning model to predict wine quality. Given the need to identify influential properties, a model like RandomForestRegressor will be chosen for its ability to provide feature importances. The data will be split into training and testing sets, and the model will be trained.

**Reasoning**:
I need to import necessary libraries, define features and target, split the dataset, instantiate the model, and then train the RandomForestRegressor model as per the instructions.
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# Define features (X) and target (y)
X = df.drop('quality', axis=1)
y = df['quality']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

# Instantiate RandomForestRegressor model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

import joblib
# Save artifacts for main.py (API)
joblib.dump(model, "wine_model.joblib")
joblib.dump(scaler, "scaler.joblib")

print("RandomForestRegressor model trained and artifacts saved successfully.")

"""## Model Evaluation and Interpretation

### Subtask:
Evaluate the trained model's performance and interpret the feature importances. Extract and visualize the feature importances from the `RandomForestRegressor` model to identify the most influential chemical and physical properties affecting wine quality.

**Reasoning**:
Now that the `RandomForestRegressor` model has been trained, we can extract and visualize the feature importances. This will help us identify which chemical and physical properties are most influential in predicting wine quality, directly addressing the core problem statement.
"""

# Get feature importances from the trained model
feature_importances = model.feature_importances_

# Create a DataFrame for better visualization
features_df = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importances})

# Sort features by importance in descending order
features_df = features_df.sort_values(by='Importance', ascending=False)

# Display the sorted feature importances
print("Feature Importances:")
display(features_df)

# Plot feature importances
plt.figure(figsize=(12, 7))
sns.barplot(x='Importance', y='Feature', data=features_df, palette='viridis')
plt.title('Feature Importances for Wine Quality Prediction')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

"""**Analysis of Feature Importances:**

The bar plot above clearly illustrates the relative importance of each chemical and physical property in predicting wine quality according to the trained Random Forest Regressor model. Features with higher importance scores contribute more significantly to the model's predictions.

From this visualization, we can identify the key drivers of wine quality. This information is crucial for Vino Veritas to focus on specific properties for quality improvement and consistency.

## Data-Driven Recommendations

Based on the feature importance analysis, the following recommendations are provided to Vino Veritas to improve wine quality and consistency:

### 1. Focus on Alcohol Content Management
*   **Insight**: Alcohol content was identified as the most significant predictor of wine quality. This suggests that precise control and optimization of the fermentation process to achieve desired alcohol levels are critical.
*   **Recommendation**: Implement stricter monitoring and control mechanisms for sugar content in grapes and yeast activity during fermentation to consistently hit optimal alcohol percentages. Experiment with different yeast strains or fermentation temperatures to fine-tune alcohol production. Consider reviewing grape harvesting times to manage initial sugar levels.

### 2. Optimize Sulphate Levels
*   **Insight**: Sulphates ranked as the second most important feature. Sulphates (primarily potassium bisulphate) are often added as a preservative and to prevent oxidation, but also contribute to the wine's aroma and taste profile.
*   **Recommendation**: Investigate the precise impact of sulphate concentrations on wine quality. Conduct controlled experiments to find the optimal range for sulphate additions that enhances quality without detrimental effects. Ensure consistent and accurate measurement and addition of sulphates across all batches.

### 3. Manage Volatile Acidity
*   **Insight**: Volatile acidity (VA), primarily acetic acid, is a major factor negatively impacting wine quality when too high.
*   **Recommendation**: Enhance sanitation practices in the winery to prevent microbial spoilage that leads to increased volatile acidity. Implement rigorous monitoring of VA levels throughout the winemaking process, especially during fermentation and aging, to detect and address issues early. Prompt intervention can prevent batches from being downgraded due to high VA.

### 4. Control Total Sulfur Dioxide (SO2) Levels
*   **Insight**: Total sulfur dioxide also showed significant importance, likely due to its role as an antioxidant and antimicrobial agent.
*   **Recommendation**: Develop a precise SO2 management protocol. While essential, excessive SO2 can be detected by consumers and detract from quality. Optimize SO2 additions based on wine pH, storage conditions, and target shelf life to maintain freshness and prevent spoilage without over-sulphuring.

### 5. Monitor Chlorides and pH
*   **Insight**: Chlorides and pH were also found to be moderately influential. Chlorides can impact taste (salinity), and pH affects microbial stability, SO2 effectiveness, and taste perception.
*   **Recommendation**: Implement routine testing for chloride levels, particularly if grapes are sourced from areas with high soil salinity. Maintain pH within optimal ranges through viticultural practices (e.g., canopy management, irrigation) and careful acid adjustments in the winery. Understanding the interplay between pH and other wine properties will be crucial.

### General Recommendations for Consistency:
*   **Standardize Processes**: Develop and strictly adhere to Standard Operating Procedures (SOPs) for all winemaking steps, from grape reception to bottling. This will reduce batch-to-batch variability.
*   **Advanced Analytics**: Continue to leverage data analytics to monitor process parameters and wine characteristics in real-time. This can help predict potential quality issues before they become significant problems.
*   **Sensory Evaluation Training**: Complement chemical analysis with regular, standardized sensory evaluations conducted by trained panels to correlate objective measurements with subjective quality perceptions.

By systematically addressing these key chemical and physical properties, Vino Veritas can achieve greater consistency in their red wine production and enhance overall product quality, leading to improved customer satisfaction and brand reputation.

## Programmatic Recommendation Generation Example

This code snippet demonstrates a simplified, rule-based approach to automatically generate data-driven recommendations based on the `features_df` (which contains feature importances). It iterates through the most important features and, using predefined knowledge, suggests actionable steps.

**Note**: This is a simplified example. A more sophisticated AI system would involve much deeper contextual understanding and reasoning capabilities.
"""

def generate_dynamic_recommendations(features_df, top_n=5):
    recommendations_list = []
    recommendations_list.append("### Data-Driven Recommendations (Generated Programmatically)\n")
    recommendations_list.append("Based on the runtime feature importance analysis, the following recommendations are dynamically generated to improve wine quality and consistency:\n")

    # Pre-defined knowledge base for generating recommendations
    knowledge_base = {
        'alcohol': {
            'insight': 'Alcohol content was identified as a highly significant predictor of wine quality. Precise control and optimization of fermentation are critical.',
            'action': 'Implement stricter monitoring and control mechanisms for sugar content in grapes and yeast activity during fermentation to consistently hit optimal alcohol percentages. Experiment with different yeast strains or fermentation temperatures to fine-tune alcohol production. Consider reviewing grape harvesting times to manage initial sugar levels.'
        },
        'sulphates': {
            'insight': 'Sulphates are important for preservation and contribute to aroma/taste. Their levels directly impact perceived quality.',
            'action': 'Investigate the precise impact of sulphate concentrations on wine quality. Conduct controlled experiments to find the optimal range for sulphate additions that enhances quality without detrimental effects. Ensure consistent and accurate measurement and addition of sulphates across all batches.'
        },
        'volatile acidity': {
            'insight': 'Volatile acidity (VA) is a major factor negatively impacting wine quality when too high, often indicating spoilage.',
            'action': 'Enhance sanitation practices in the winery to prevent microbial spoilage that leads to increased volatile acidity. Implement rigorous monitoring of VA levels throughout the winemaking process, especially during fermentation and aging, to detect and address issues early. Prompt intervention can prevent batches from being downgraded due to high VA.'
        },
        'total sulfur dioxide': {
            'insight': 'Total sulfur dioxide is crucial as an antioxidant and antimicrobial agent, affecting wine stability and freshness.',
            'action': 'Develop a precise SO2 management protocol. Optimize SO2 additions based on wine pH, storage conditions, and target shelf life to maintain freshness and prevent spoilage without over-sulphuring.'
        },
        'chlorides': {
            'insight': 'Chlorides can impact the taste (salinity) and mouthfeel of wine, and are moderately influential.',
            'action': 'Implement routine testing for chloride levels, particularly if grapes are sourced from areas with high soil salinity. Evaluate their impact on taste profiles through sensory analysis.'
        },
        'pH': {
            'insight': 'pH affects microbial stability, the effectiveness of SO2, and taste perception, showing moderate importance.',
            'action': 'Maintain pH within optimal ranges through viticultural practices (e.g., canopy management, irrigation) and careful acid adjustments in the winery. Understanding the interplay between pH and other wine properties will be crucial.'
        },
        'fixed acidity': {
            'insight': 'Fixed acidity contributes to the tartness and structure of the wine. An optimal balance is essential.',
            'action': 'Monitor grape ripeness closely and manage vineyard practices to achieve desired fixed acidity levels. Consider targeted acid adjustments post-fermentation if necessary to balance the wine.'
        },
        'residual sugar': {
            'insight': 'Residual sugar impacts the sweetness and mouthfeel. Its level is a balance between fermentation and desired wine style.',
            'action': 'Carefully control fermentation to achieve the target residual sugar levels, depending on the desired wine style (dry, off-dry, sweet). Implement precise measurements throughout the process.'
        },
        'citric acid': {
            'insight': 'Citric acid is a minor acid in wine but contributes to freshness and tartness.',
            'action': 'Monitor citric acid levels and their contribution to the overall acidity profile. Ensure it complements other acids without causing imbalance.'
        },
        'density': {
            'insight': 'Density is correlated with sugar content and alcohol. It provides an indication of the wine\'s concentration and body.',
            'action': 'Monitor density throughout fermentation as an indicator of sugar consumption and alcohol production. Ensure grape must density is optimal before fermentation to achieve desired wine characteristics.'
        },
        'free sulfur dioxide': {
            'insight': 'Free sulfur dioxide protects against oxidation and microbial spoilage. Maintaining adequate levels is critical.',
            'action': 'Regularly measure free SO2 levels and make precise additions to ensure adequate protection. Consider wine pH when adjusting free SO2, as its effectiveness is pH-dependent.'
        }
    }

    # Get top N features or all if less than top_n
    top_features = features_df.head(top_n)

    for i, row in top_features.iterrows():
        feature_name = row['Feature']
        importance_score = row['Importance']

        if feature_name in knowledge_base:
            entry = knowledge_base[feature_name]
            recommendations_list.append(f"### {i+1}. Focus on {feature_name.replace('_', ' ').title()} Management (Importance: {importance_score:.3f})\n")
            recommendations_list.append(f"*   **Insight**: {entry['insight']}\n")
            recommendations_list.append(f"*   **Recommendation**: {entry['action']}\n")
        else:
            # Fallback for features not explicitly in the knowledge base
            recommendations_list.append(f"### {i+1}. Investigate {feature_name.replace('_', ' ').title()} (Importance: {importance_score:.3f})\n")
            recommendations_list.append(f"*   **Insight**: This property has a significant impact on wine quality according to the model.\n")
            recommendations_list.append(f"*   **Recommendation**: Conduct further research and controlled experiments to understand the specific mechanisms through which {feature_name.replace('_', ' ')} affects wine quality and how its levels can be optimally managed in production.\n")

    recommendations_list.append("\n### General Recommendations for Consistency (Static)\n")
    recommendations_list.append("*   **Standardize Processes**: Develop and strictly adhere to Standard Operating Procedures (SOPs) for all winemaking steps, from grape reception to bottling. This will reduce batch-to-batch variability.\n")
    recommendations_list.append("*   **Advanced Analytics**: Continue to leverage data analytics to monitor process parameters and wine characteristics in real-time. This can help predict potential quality issues before they become significant problems.\n")
    recommendations_list.append("*   **Sensory Evaluation Training**: Complement chemical analysis with regular, standardized sensory evaluations conducted by trained panels to correlate objective measurements with subjective quality perceptions.\n")

    return "\n".join(recommendations_list)

# Generate and display the recommendations for all features
dynamic_recs = generate_dynamic_recommendations(features_df, top_n=len(features_df))
print(dynamic_recs)

# Generate and display the recommendations for all features
dynamic_recs = generate_dynamic_recommendations(features_df, top_n=len(features_df))
print(dynamic_recs)